version: '3.9'

services:
  api:
    build: .
    ports:
    - "5001:5001"
    volumes:
    - .:/opt
    depends_on: 
    - mongo
  
  mongo:
    image: mongo
    volumes:
    - mongo-data:/data/db
    - mongo-configdb:/data/configdb

volumes:
  mongo-data:
  mongo-configdb: